sudo: false
dist: trusty
language: bash
branches:
  only:
  - master
script:
- bash build_deb.sh
- ls
before_deploy:
- ls
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: "NR6dB1igts8AG88cluWcJk8SsgVlN9r4Iw1kIdtUMsnkmN7R6VT9wd6suQr21Sdn77UV/OmR+aSw7p4XKzI1nlNso+i+wWsPxhYCiTAhi2btynd9zOneZHYM2VtroXpn+V6/PaMhc4kfdnvfoOTsdYjRBEVFltVe6/PQCHGZiUZ8y0+CSZ8p+B/GqD6nZ1YuI45oEWQAkj7kQITYMiAS+a9tbSBx8qbiljgpgK1k1KHJkHh9xwXianEW+/pb245KcyPlPLbncgP2MfBjaGBQR6/3/qVNHKNKgy7URjp+jM+82HZD0EIeMbh0gYhcpdorpIQlaXKR2DmX7X74GFoVJpmczdPdiUj+iiBRXoyZtP/PeCK2HBUQBUFVNzJf1XEccPkIAo7gEXKBN2AcjZOL6V7u0xDTUYBM2i3YGnXHqLpeUy4LAjOM6TrzGkJ2Xw+A7ca6QzTd3Yd72x4J+ziTUfcUHsxPvvNh92cYAQHLyMEfXnNz+ofbg6L17WRRAjNV/5iibr27/VhBCIAoXg0R+Ah7au9RJVnnP6qPmU40uFrokBJS+/c6lLVVD7l8ihsQQGAvkJeA1pvjzWRCY18Nr33VMTnYHotPg/U446uuieTrRZTODDJr3aobgHb9Uf+2X+ZYx6ZoTpduPAJozk178mIncXHIgGzF/VQu24j/pas="
  local_dir: "build/"
  on:
    branch: master
