sudo: false
dist: trusty
language: bash
branches:
  only:
  - master
script:
- bash build_deb.sh
- ls
before_deploy:
- ls
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: "kIppZ5XfOXd2Q1KcUgTmg0Pp1nJ87oA4J+ALCq6iB5Nr0eCUL9O4XrZcEq5wMuKgl/9mDl5U9LIWrxkVfjnwHM8zLCofhScxecqYV5vIGwrMqIieSMJizX+5A93yYjan8aZdsrrsjd7n2jOlfApreycOAWj8os9MLp5n+c2Bis3y/B6YUR2K1IICvp9MsO7kiDFcRxn37AxAf9EvkeYGhgqqMJorzXaMolCz6tRW6HMwqrW2zAqlYkir1xNWcus/29aUy/L1pQAla04WdltK4+2CUKAZaOfLzhb4nOPzaRdYzgPozs1HmfV5aOkTluM/wcrxXaroqXqBw5WCco65tG1C4wSMWl5bQrA+562zo55EBOq4yXKgAqHKTIj1WXhAI0YNixpItoHxo/ZIyRhAN0DJx7SHwOFYoNHNwQVUD62nVhiVqMNAu7JN9v+tq0dOtq5jDm/pOyQMXfM7rz+dEIv75xZeUisMAMctAhL9PRwFFLu7gsJFgSK1UgOs5bBeK5Ns4J6oohQpT39nEvDNOoUu2ccjxCSm6Ski3/nE/cWJwuOPopCGJNeac29rcMYxZ6rsa/quk/tRx/bVKJtD2pkZNrLt6EA6ogTh4jbzmuemjsq8xRsiibHWry9RR8RUw44wwyzU5OXnx+APnYxavzsUoh5qnvlS63MvbKwr4fU="
  local_dir: "build/"
  on:
    branch: master
